package llm

import (
	"context"
	"errors"
	"strings"
	"unicode"

	"go.uber.org/zap"

	"github.com/globussoft/callified-backend/internal/config"
)

// Provider routes LLM calls to Gemini or Groq and handles streaming sentence splitting.
// Language "mr" (Marathi) always uses Gemini for better Devanagari support.
// All other languages use LLM_PROVIDER env var (default: gemini).
type Provider struct {
	gemini *GeminiClient
	groq   *GroqClient
	cfg    *config.Config
	log    *zap.Logger
}

// NewProvider creates a Provider wired to Gemini and Groq from cfg.
func NewProvider(cfg *config.Config, log *zap.Logger) *Provider {
	return &Provider{
		gemini: NewGeminiClient(cfg.GeminiAPIKey, cfg.GeminiModel, cfg.GeminiBaseURL),
		groq:   NewGroqClient(cfg.GroqAPIKey, cfg.GroqModel),
		cfg:    cfg,
		log:    log,
	}
}

// ProcessTranscript calls the selected LLM, streams the response, splits it into
// sentences via SplitBuffer, detects [HANGUP], and calls onSentence for each sentence.
// Mirrors Python ws_handler.py _process_transcript LLM section.
func (p *Provider) ProcessTranscript(ctx context.Context, req TranscriptRequest, onSentence func(SentenceChunk)) error {
	var buf strings.Builder

	// All languages follow LLM_PROVIDER config.
	useGemini := p.cfg.LLMProvider != "groq"
	providerName := "groq"
	if useGemini {
		providerName = "gemini"
	}
	p.log.Info("[LLM] processing transcript",
		zap.String("provider", providerName),
		zap.String("language", req.Language),
		zap.Int32("max_tokens", req.MaxTokens),
	)

	onToken := func(token string) {
		buf.WriteString(token)
		sentences, remainder := SplitBuffer(buf.String())
		buf.Reset()
		buf.WriteString(remainder)
		for _, sent := range sentences {
			if text, hangup := parseChunk(sent); text != "" || hangup {
				onSentence(SentenceChunk{Text: text, HasHangup: hangup})
			}
		}
	}

	var err error
	if useGemini {
		err = p.gemini.StreamTokens(ctx, req, onToken)
	} else {
		err = p.groq.StreamTokens(ctx, req, onToken)
	}

	// Flush any text left in the buffer after stream ends (no trailing punctuation).
	// Realtime inbound calls should not speak this remainder, because it often
	// sounds like a sentence cut off in the middle when the model stops without
	// punctuation.
	if remaining := strings.TrimSpace(buf.String()); remaining != "" && !errors.Is(err, ErrMaxTokens) && !req.DropIncompleteRemainder {
		text, hangup := parseChunk(remaining)
		if text != "" || hangup {
			onSentence(SentenceChunk{Text: text, HasHangup: hangup})
		}
	}

	return err
}

// ClassifyRepeatIntent returns a stable semantic key for repeated-question
// detection. The key is generated by the LLM so semantically identical
// questions in different languages can match without a hardcoded intent list.
func (p *Provider) ClassifyRepeatIntent(ctx context.Context, text, language string) (string, error) {
	text = strings.TrimSpace(text)
	if text == "" {
		return "", nil
	}
	systemPrompt := strings.TrimSpace(`
You classify one customer utterance for repeated-question detection in an outbound sales call.
Return only one short snake_case semantic intent key, or "none".
Use the same key when the customer asks the same meaning in any language.
Return "none" for acknowledgements, filler sounds, greetings, or plain answers.
Do not explain. Do not add punctuation. Do not include a fixed category unless it captures the actual meaning.
`)
	history := []ChatMessage{{
		Role: "user",
		Text: "Language: " + language + "\nCustomer: " + text,
	}}
	resp, err := p.GenerateResponse(ctx, systemPrompt, history, 32)
	if err != nil {
		return "", err
	}
	return sanitizeRepeatIntentKey(resp), nil
}

func sanitizeRepeatIntentKey(text string) string {
	text = strings.ToLower(strings.TrimSpace(text))
	text = strings.Trim(text, "`\"' .,:;!?()[]{}")
	var b strings.Builder
	lastUnderscore := false
	for _, r := range text {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
			lastUnderscore = false
		case r == '_' || unicode.IsSpace(r) || r == '-' || r == '/':
			if !lastUnderscore && b.Len() > 0 {
				b.WriteByte('_')
				lastUnderscore = true
			}
		}
		if b.Len() >= 64 {
			break
		}
	}
	key := strings.Trim(b.String(), "_")
	switch key {
	case "", "none", "no_intent", "unknown", "filler", "greeting", "acknowledgement", "acknowledgment":
		return ""
	default:
		return key
	}
}

// GenerateResponse calls the LLM without streaming and returns the full reply.
// Used by WA agent, prompt generation, and other non-real-time contexts.
func (p *Provider) GenerateResponse(ctx context.Context, systemPrompt string, history []ChatMessage, maxTokens int32) (string, error) {
	req := TranscriptRequest{
		Transcript:   "", // will use last message from history
		SystemPrompt: systemPrompt,
		History:      history,
		MaxTokens:    maxTokens,
	}
	// Extract the last user message as the transcript
	for i := len(history) - 1; i >= 0; i-- {
		if history[i].Role == "user" {
			req.Transcript = history[i].Text
			req.History = history[:i]
			break
		}
	}

	useGemini := p.cfg.LLMProvider != "groq"
	var result strings.Builder
	onToken := func(t string) { result.WriteString(t) }

	var err error
	if useGemini {
		err = p.gemini.StreamTokens(ctx, req, onToken)
	} else {
		err = p.groq.StreamTokens(ctx, req, onToken)
	}
	return strings.TrimSpace(result.String()), err
}

// GenerateText calls Gemini (non-streaming) with thinking disabled.
// Suitable for batch extraction tasks like product scraping and prompt generation.
func (p *Provider) GenerateText(ctx context.Context, systemPrompt, userMessage string, maxOutputTokens int) (string, error) {
	return p.gemini.GenerateText(ctx, systemPrompt, userMessage, maxOutputTokens)
}

// parseChunk strips [HANGUP] from text and returns (cleanText, hasHangup).
func parseChunk(text string) (string, bool) {
	hasHangup := strings.Contains(text, "[HANGUP]")
	clean := strings.TrimSpace(strings.ReplaceAll(text, "[HANGUP]", ""))
	clean = stripBracketedMeta(clean)
	return clean, hasHangup
}

// stripBracketedMeta removes non-spoken model side-notes such as
// "[The user said ...]" that occasionally leak from the LLM. The voice path
// must speak only customer-facing text; [HANGUP] is handled before this runs.
func stripBracketedMeta(text string) string {
	for {
		start := strings.Index(text, "[")
		if start == -1 {
			return strings.TrimSpace(text)
		}
		end := strings.Index(text[start:], "]")
		if end == -1 {
			if start == 0 {
				return ""
			}
			return strings.TrimSpace(text[:start])
		}
		end += start
		text = strings.TrimSpace(text[:start] + " " + text[end+1:])
	}
}
