import React from 'react';
import {
  AimOutlined,
  ApiOutlined,
  AlertOutlined,
  AudioOutlined,
  BarChartOutlined,
  BankOutlined,
  BellOutlined,
  BookOutlined,
  BulbOutlined,
  CalendarOutlined,
  CameraOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  ClearOutlined,
  CloseOutlined,
  CloudUploadOutlined,
  CopyOutlined,
  CustomerServiceOutlined,
  DeleteOutlined,
  DesktopOutlined,
  DisconnectOutlined,
  DownOutlined,
  EditOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileTextOutlined,
  FilePdfOutlined,
  FolderOpenOutlined,
  FormOutlined,
  GlobalOutlined,
  HistoryOutlined,
  InfoCircleOutlined,
  InboxOutlined,
  LinkOutlined,
  LoadingOutlined,
  MailOutlined,
  MessageOutlined,
  MobileOutlined,
  MutedOutlined,
  PauseCircleOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlayCircleOutlined,
  PlusOutlined,
  PrinterOutlined,
  ProductOutlined,
  RedoOutlined,
  RightOutlined,
  RobotOutlined,
  SaveOutlined,
  SearchOutlined,
  SettingOutlined,
  SafetyCertificateOutlined,
  SoundOutlined,
  StopOutlined,
  TagOutlined,
  TeamOutlined,
  ToolOutlined,
  ThunderboltOutlined,
  UploadOutlined,
  UserOutlined,
  WarningOutlined,
} from '@ant-design/icons';

const icons = {
  aim: AimOutlined,
  api: ApiOutlined,
  alert: AlertOutlined,
  archive: InboxOutlined,
  audio: AudioOutlined,
  chart: BarChartOutlined,
  bank: BankOutlined,
  bell: BellOutlined,
  book: BookOutlined,
  idea: BulbOutlined,
  calendar: CalendarOutlined,
  camera: CameraOutlined,
  checkCircle: CheckCircleOutlined,
  check: CheckOutlined,
  clear: ClearOutlined,
  close: CloseOutlined,
  upload: CloudUploadOutlined,
  copy: CopyOutlined,
  takeover: CustomerServiceOutlined,
  delete: DeleteOutlined,
  desktop: DesktopOutlined,
  disconnect: DisconnectOutlined,
  down: DownOutlined,
  edit: EditOutlined,
  environment: EnvironmentOutlined,
  experiment: ExperimentOutlined,
  hide: EyeInvisibleOutlined,
  show: EyeOutlined,
  file: FileTextOutlined,
  pdf: FilePdfOutlined,
  folder: FolderOpenOutlined,
  note: FormOutlined,
  global: GlobalOutlined,
  history: HistoryOutlined,
  info: InfoCircleOutlined,
  link: LinkOutlined,
  loading: LoadingOutlined,
  mail: MailOutlined,
  message: MessageOutlined,
  mobile: MobileOutlined,
  muted: MutedOutlined,
  pause: PauseCircleOutlined,
  phone: PhoneOutlined,
  image: PictureOutlined,
  play: PlayCircleOutlined,
  plus: PlusOutlined,
  print: PrinterOutlined,
  product: ProductOutlined,
  retry: RedoOutlined,
  right: RightOutlined,
  robot: RobotOutlined,
  save: SaveOutlined,
  search: SearchOutlined,
  settings: SettingOutlined,
  shield: SafetyCertificateOutlined,
  sound: SoundOutlined,
  stop: StopOutlined,
  tag: TagOutlined,
  team: TeamOutlined,
  tool: ToolOutlined,
  power: ThunderboltOutlined,
  import: UploadOutlined,
  user: UserOutlined,
  warning: WarningOutlined,
};

export default function AppIcon({ name, ...props }) {
  const Icon = icons[name];
  return Icon ? <Icon aria-hidden="true" {...props} /> : null;
}
